version: 2
updates:
  # Maintain dependencies for root (Frontend/pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for server (Backend/npm)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"

  # Maintain dependencies for yolo-service (AI service/pip)
  - package-ecosystem: "pip"
    directory: "/yolo-service"
    schedule:
      interval: "weekly"
